"""
Event system for backtesting engine

Implements event-driven architecture with MarketEvent, SignalEvent,
OrderEvent, and FillEvent to prevent look-ahead bias.
"""

from enum import Enum
from dataclasses import dataclass
from datetime import datetime
from typing import Any, Dict, Optional


class EventType(Enum):
    """Event types for backtesting system"""
    MARKET = "MARKET"
    SIGNAL = "SIGNAL"
    ORDER = "ORDER"
    FILL = "FILL"


@dataclass
class BaseEvent:
    """Base class for all events"""
    type: EventType
    timestamp: datetime


@dataclass
class MarketEvent(BaseEvent):
    """
    Market data event containing OHLCV data for a symbol

    Triggered when new market data arrives for a symbol.
    Used to update portfolio mark-to-market values.
    """
    symbol: str
    data: Dict[str, Any]  # Contains price, volume, etc.

    def __init__(self, timestamp: datetime, symbol: str, data: Dict[str, Any]):
        super().__init__(EventType.MARKET, timestamp)
        self.symbol = symbol
        self.data = data


@dataclass
class SignalEvent(BaseEvent):
    """
    Signal event generated by a strategy

    Contains trading signal (LONG/SHORT) and originating strategy.
    Consumed by portfolio to generate OrderEvents.
    """
    symbol: str
    signal_type: str  # 'LONG' or 'SHORT'
    strategy_id: str
    strength: float = 1.0

    def __init__(self, timestamp: datetime, symbol: str, signal_type: str, strategy_id: str, strength: float = 1.0):
        super().__init__(EventType.SIGNAL, timestamp)
        self.symbol = symbol
        self.signal_type = signal_type
        self.strategy_id = strategy_id
        self.strength = strength


@dataclass
class OrderEvent(BaseEvent):
    """
    Order event to be executed

    Contains order details to be processed by execution handler.
    Generated from SignalEvents by portfolio manager.
    """
    symbol: str
    order_type: str  # 'MKT', 'LMT'
    quantity: int
    direction: str   # 'BUY' or 'SELL'
    price: Optional[float] = None

    def __init__(self, timestamp: datetime, symbol: str, order_type: str, quantity: int, direction: str, price: Optional[float] = None):
        super().__init__(EventType.ORDER, timestamp)
        self.symbol = symbol
        self.order_type = order_type
        self.quantity = quantity
        self.direction = direction
        self.price = price


@dataclass
class FillEvent(BaseEvent):
    """
    Order fill event with execution details

    Contains actual fill price, commission, and slippage.
    Generated by execution handler after simulating order execution.
    """
    symbol: str
    order_type: str
    quantity: int
    direction: str
    fill_cost: float    # Price * quantity + commission
    commission: float

    def __init__(self, timestamp: datetime, symbol: str, order_type: str, quantity: int, direction: str, fill_cost: float, commission: float):
        super().__init__(EventType.FILL, timestamp)
        self.symbol = symbol
        self.order_type = order_type
        self.quantity = quantity
        self.direction = direction
        self.fill_cost = fill_cost
        self.commission = commission